#大学初期値CSVファイル
initial_college_csv = "u2020v03.csv"

#接地用　２年目以降の入学定員・収容人数CSVフォルダー
enroll_capa_csv_dir = "capa/"
#接地用　入学定員・収容人数CSVファイル名のテンプレート。前にYYYYがつく。
enroll_capa_csv_name = "_enroll_capa.csv"
#接地用  入学定員・収容人数CSVを辞書化した配列のエントリーポイント。ダミー。
enroll_capa_dics = []

#シミュレーション開始年度
start_year = 2020
#シミュレーション実行回数
epochs = 12

#学生数初期値 2014〜学生基本調査
#上段は2014から2021まで。2021は旺文社の推計値。2014-2020はe-Statの集計値
#下段は2020-2031年の推計値。上段の値で単回帰した値
#student_number = [657410,    661676,    660060,    673655,    673547,    668390,    659135,    632000,
#    651858,    649885,    647913,    645940,    643968,    641995,    640023,    638050,    636077,    634105]
#
#2021.11.19 2020年の志願者と18歳人口の比率をもとに、文科省試算の18歳人口から計算した2020年から2031
student_number = [659135,644337,633121, 619473,600142,615444,616657,613526,604431,603202,592806,584150]

#2021.11.19 受験生偏差値の平均と標準偏差 2018データから
#𝜇 =54.9578,𝜎=8.8676
student_dev_mu = 54.9578
student_dev_sigma = 8.8676

#乱数シード初期値 u64
random_seed = 42

#データ出力先　親ディレクトリ
output_dir_base = "./output"

#データ出力先ディレクトリ　親＋日時
#実行時に決定するので暫定値をカレントにしておく
output_dir = "."

#国公立出願確率
national_prob = 0.8120

#国公立大学選択時の偏差値上限と下限
national_range = [0, 5]

#ランク別私立大学グループの偏差値上限と下限
#自分の偏差値+lower 〜　自分の偏差値+upper
# 0:（チャレンジ校） 1:（本命校） 2:（安全校）
college_rank_lower = [3, -3, -5]
college_rank_upper = [5,  3, -3]

#各ランクから何校選ぶか
# 0:（チャレンジ校） 1:（本命校） 2:（安全校）
#college_rank_select_number = [5, 3, 2]
#2021.11.19 2延べ8校と7校の２パターンを用意
college_rank_select_number = [
    [4, 2, 1], # [0]7校選択
    [5, 2, 1], # [1]8校選択
]

#併願パターン選択確率
#  国公立専願、併願、私立専願　の合計が100
#  2021.10.04現在　
#  apply_pattern_rate = [1, 14, 85]

#2021.11.19
#平均出願数が7.5542（2020年度実績）になるように
#出願数7校or8校とした場合の7校になるBernoulli(p)
first_pattern_rate = 0.4458

#目標合格者総数中の追加合格の割合
#  2021.10.04
enroll_add_rate = 0

#追加合格時の偏差値下限。
#  大学偏差値から幾ら下までを許容するか
#  0なら偏差値足切りなし
#  2021.10.04
enroll_add_lower = 0

#出願時同一グループ内大学選択確率を
#一様ではなく大学の入学定員に比例させるか
college_select_by_enroll = true

# 2021.12.07 大学偏差値更新有無
update_dev = false

# 2021.11.23 接地用シミュレーションか？
grounding = false

#2021.12.07 地方、小規模大学の入学定員超過率緩和
# 支援策を実行するか
# シナリオ1 現状維持の場合false
small_college_support = true
senario = 2

#2021.12.07 支援する場合の
# 2022以降の入学定員超過率 [大,中,小]
# シナリオ2 一律厳格化
new_limits = [1.0, 1.0, 1.0]

#2021.12.11 ログ出力有無の制御
logging = false

#2021.12.12 合格者数計算ロジックのバージョン　1 or 2
enroll_algo_version = 2

#2021.12.12 2020年度の私立大学平均歩留率
mean_yield_rate = 0.5293

#2021.12.31 大学偏差値上限と下限．最低クラス最高クラスの学生の併願数が1になるのを緩和.1000倍の整数
college_dev_rift = false
college_dev_lower = 36348
college_dev_upper = 78195

#2021.12.32 偏差値平均以下学生はダイアモンド受験
college_rank_select_number_diamond = [
    [2, 3, 2], # [0]7校選択
    [2, 4, 2], # [1]8校選択
]
#2021.01.01  今年度超過率に対する感度　乗じる
sensitivity = 0.7
