#大学初期値CSVファイル
initial_college_csv = "../../sim/u2020v01.csv"

#シミュレーション開始年度
start_year = 2020
#シミュレーション実行回数
epochs = 12

#学生数初期値 2014〜学生基本調査
#上段は2014から2021まで。2021は旺文社の推計値。2014-2020はe-Statの集計値
#下段は2020-2031年の推計値。上段の値で単回帰した値
#student_number = [657410,    661676,    660060,    673655,    673547,    668390,    659135,    632000,
#    651858,    649885,    647913,    645940,    643968,    641995,    640023,    638050,    636077,    634105]
#
#2021.11.19 2020年の志願者と18歳人口の比率をもとに、文科省試算の18歳人口から計算した2020年から2031
student_number = [659135,644337,633121, 619473,600142,615444,616657,613526,604431,603202,592806,584150]

#2021.11.19 受験生偏差値の平均と標準偏差 2018データから
#𝜇 =54.9578,𝜎=8.8676
student_dev_mu = 54.9578
student_dev_sigma = 8.8676

#乱数シード初期値 u64
random_seed = 42

#データ出力先　親ディレクトリ
output_dir_base = "./output"

#データ出力先ディレクトリ　親＋日時
#実行時に決定するので暫定値をカレントにしておく
output_dir = "."

#国公立出願確率
national_prob = 0.8120

#国公立大学選択時の偏差値上限と下限
national_range = [0, 5]

#ランク別私立大学グループの偏差値上限と下限
#自分の偏差値+lower 〜　自分の偏差値+upper
# 0:（チャレンジ校） 1:（本命校） 2:（安全校）
college_rank_lower = [3, -3, -5]
college_rank_upper = [5,  3, -3]

#各ランクから何校選ぶか
# 0:（チャレンジ校） 1:（本命校） 2:（安全校）
#college_rank_select_number = [5, 3, 2]
#2021.11.19 2延べ8校と7校の２パターンを用意
college_rank_select_number = [
    [4, 2, 1], # [0]7校選択
    [5, 2, 1], # [1]8校選択
]

#併願パターン選択確率
#  国公立専願、併願、私立専願　の合計が100
#  2021.10.04現在　
#  apply_pattern_rate = [1, 14, 85]

#2021.11.19
#平均出願数が7.5542（2020年度実績）になるように
#出願数7校or8校とした場合の7校になるBernoulli(p)
first_pattern_rate = 0.4458

#目標合格者総数中の追加合格の割合
#  2021.10.04
enroll_add_rate = 0

#追加合格時の偏差値下限。
#  大学偏差値から幾ら下までを許容するか
#  0なら偏差値足切りなし
#  2021.10.04
enroll_add_lower = 0

#出願時同一グループ内大学選択確率を
#一様ではなく大学の入学定員に比例させるか
college_select_by_enroll = true
