#大学初期値CSVファイル
initial_college_csv = "../../sim/u2014v01.csv"

#接地用　２年目以降の入学定員・収容人数CSVフォルダー
enroll_capa_csv_dir = "../../sim/capa/"
#接地用　入学定員・収容人数CSVファイル名のテンプレート。前にYYYYがつく。
enroll_capa_csv_name = "_enroll_capa.csv"
#接地用  入学定員・収容人数CSVを辞書化した配列のエントリーポイント。ダミー。
enroll_capa_dics = []

#シミュレーション開始年度
start_year = 2014
#シミュレーション実行回数
epochs = 7

# 2021.11.23 接地用シミュレーションか？
grounding = true

#学生数初期値 2014〜学生基本調査
#上段は2014から2021まで。2021は旺文社の推計値。2014-2020はe-Statの集計値
#下段は2020-2031年の推計値。上段の値で単回帰した値
student_number = [657410,    661676,    660060,    673655,    673547,    668390,    659135,    632000,
    651858,    649885,    647913,    645940,    643968,    641995,    640023,    638050,    636077,    634105]

#受験生偏差値の平均と標準偏差
student_dev_mu = 53.947
student_dev_sigma = 9.268

#乱数シード初期値 u64
random_seed = 42

#データ出力先　親ディレクトリ
output_dir_base = "./output"

#データ出力先ディレクトリ　親＋日時
#実行時に決定するので暫定値をカレントにしておく
output_dir = "."

#国公立出願確率
national_prob = 0.47242

#国公立大学選択時の偏差値上限と下限
national_range = [0, 5]

#ランク別私立大学グループの偏差値上限と下限
#自分の偏差値+lower 〜　自分の偏差値+upper
# 0:（チャレンジ校） 1:（本命校） 2:（安全校）
college_rank_lower = [3, -3, -5]
college_rank_upper = [5,  3, -3]

#各ランクから何校選ぶか
# 0:（チャレンジ校） 1:（本命校） 2:（安全校）
#college_rank_select_number = [5, 3, 2]
#2021.10.11 2延べ7校と6校の２パターンを用意
#2021.11.24 真ん中を１つ増やしてみる。
college_rank_select_number = [
    [3, 3, 1], # [0]7校選択
    [4, 3, 1], # [1]8校選択
]

#併願パターン選択確率
#  国公立専願、併願、私立専願　の合計が100
#  2021.10.04現在　
#  apply_pattern_rate = [1, 14, 85]
#2021.10.11
#平均出願数が6.1898（2014年度実績）になるように
#出願数6校or7校とした場合の6校になるBernoulli(p)
first_pattern_rate = 0.8102

#目標合格者総数中の追加合格の割合
#  2021.10.04
enroll_add_rate = 0

#追加合格時の偏差値下限。
#  大学偏差値から幾ら下までを許容するか
#  0なら偏差値足切りなし
#  2021.10.04
enroll_add_lower = 0

#出願時同一グループ内大学選択確率を
#一様ではなく大学の入学定員に比例させるか
college_select_by_enroll = true

#小規模大学の緩和後超過率　0は緩和しない
small_college_rate = 0

#大学偏差値更新有無
update_dev = true
