######################################################
# 2021.12.01 21:30 偏差値更新なし
######################################################

#大学初期値CSVファイル
initial_college_csv = "../../sim/u2014v05.csv"

#接地用　２年目以降の入学定員・収容人数CSVフォルダー
enroll_capa_csv_dir = "../../sim/capa/"
#接地用　入学定員・収容人数CSVファイル名のテンプレート。前にYYYYがつく。
enroll_capa_csv_name = "_enroll_capa.csv"
#接地用  入学定員・収容人数CSVを辞書化した配列のエントリーポイント。ダミー。
enroll_capa_dics = []

#シミュレーション開始年度
start_year = 2014
#シミュレーション実行回数
epochs = 7

# 2021.11.23 接地用シミュレーションか？
grounding = true

#学生数初期値 2014〜学生基本調査
#上段は2014から2021まで。2021は旺文社の推計値。2014-2020はe-Statの集計値
#下段は2020-2031年の推計値。上段の値で単回帰した値
student_number = [657410,    661676,    660060,    673655,    673547,    668390,    659135,    632000,
    651858,    649885,    647913,    645940,    643968,    641995,    640023,    638050,    636077,    634105]

#受験生偏差値の平均と標準偏差
student_dev_mu = 53.947
student_dev_sigma = 9.268

#乱数シード初期値 u64
random_seed = 42

#データ出力先　親ディレクトリ
output_dir_base = "./output"

#データ出力先ディレクトリ　親＋日時
#実行時に決定するので暫定値をカレントにしておく
output_dir = "."

#国公立出願確率
national_prob = 0.47242

#国公立大学選択時の偏差値上限と下限
national_range = [0, 5]

#ランク別私立大学グループの偏差値上限と下限
#自分の偏差値+lower 〜　自分の偏差値+upper
# 0:（チャレンジ校） 1:（本命校） 2:（安全校）
college_rank_lower = [3, -3, -5]
college_rank_upper = [5,  3, -3]

#各ランクから何校選ぶか
# 0:（チャレンジ校） 1:（本命校） 2:（安全校）
#college_rank_select_number = [5, 3, 2]
#2021.10.11 2延べ7校と6校の２パターンを用意
college_rank_select_number = [
    [3, 2, 1], # [0]6校選択
    [4, 2, 1], # [1]7校選択
]

#併願パターン選択確率
#  国公立専願、併願、私立専願　の合計が100
#  2021.10.04現在　
#  apply_pattern_rate = [1, 14, 85]
#2021.10.11
#平均出願数が6.1898（2014年度実績）になるように
#出願数6校or7校とした場合の6校になるBernoulli(p)
first_pattern_rate = 0.8102

#目標合格者総数中の追加合格の割合
#  2021.10.04
enroll_add_rate = 0

#追加合格時の偏差値下限。
#  大学偏差値から幾ら下までを許容するか
#  0なら偏差値足切りなし
#  2021.10.04
enroll_add_lower = 0

#出願時同一グループ内大学選択確率を
#一様ではなく大学の入学定員に比例させるか
college_select_by_enroll = true

#小規模大学の緩和後超過率　0は緩和しない
small_college_rate = 0

#大学偏差値更新有無
update_dev = false

#本番のみ使用
#2021.12.07 地方、小規模大学の入学定員超過率緩和
# 支援策を実行するか
# シナリオ1 現状維持の場合false
small_college_support = false
#2021.12.11 シナリオ番号．設定の場合は0
senario = 0

#本番のみ使用
#2021.12.07 支援する場合の
# 2022以降の入学定員超過率 [大,中,小]
# シナリオ2 一律厳格化
new_limits = [1.0, 1.0, 1.0]

#2021.12.11 ログ出力有無の制御
logging = true

#2021.12.12 合格者数計算ロジックのバージョン　1 or 2
enroll_algo_version = 1

#2021.12.12 2014年度の私立大学平均歩留率
mean_yield_rate = 0.5566

#2021.12.31 大学偏差値上限と下限．最低クラス最高クラスの学生の併願数が1になるのを緩和.1000倍の整数
college_dev_rift = false
college_dev_lower = 36348
college_dev_upper = 78195

#2021.12.31 偏差値平均以下学生はダイアモンド受験
college_rank_select_number_diamond = [
    [1, 3, 2], # [0]6校選択
    [2, 3, 2], # [1]7校選択
]

#2022.01.01  今年度超過率に対する感度　乗じる
sensitivity = 1.0

#2021.01.02  二次発表（国公立）結果で決定せず，浪人覚悟で追加合格を待つ学生の割合
wait_addtion_rate = 0.4

